# Generated by Django 3.1.1 on 2021-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeYouRead',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('option5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BeforeYouReadAns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('numofchoose1', models.IntegerField()),
                ('numofchoose2', models.IntegerField()),
                ('numofchoose3', models.IntegerField()),
                ('numofchoose4', models.IntegerField()),
                ('numofchoose5', models.IntegerField()),
                ('totalchoose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FocusOnContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('lesson', models.IntegerField(default=None)),
                ('questionnum', models.CharField(default=None, max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FocusOnContentAns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('lesson', models.IntegerField()),
                ('questionnum', models.CharField(default=None, max_length=100)),
                ('correctoption', models.CharField(max_length=100)),
                ('chooseoption1', models.IntegerField()),
                ('chooseoption2', models.IntegerField()),
                ('chooseoption3', models.IntegerField()),
                ('chooseoption4', models.IntegerField()),
                ('totalchoose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_spend', models.CharField(max_length=50)),
                ('money', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('isPri', models.BooleanField()),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentcheck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cId', models.CharField(max_length=10)),
                ('cName', models.CharField(max_length=10)),
                ('cGroup', models.IntegerField(null=True)),
                ('FirstweekCheck', models.CharField(max_length=10)),
                ('SecondweekCheck', models.CharField(max_length=10)),
                ('ThirdweekCheck', models.CharField(max_length=10)),
                ('ForthweekCheck', models.CharField(max_length=10)),
                ('point', models.IntegerField(null=True)),
                ('picked', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyPreview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('lesson', models.IntegerField()),
                ('questionnum', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correctans', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyPreviewAns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('lesson', models.IntegerField()),
                ('cId', models.CharField(max_length=10)),
                ('q1answer', models.CharField(max_length=100)),
                ('q2answer', models.CharField(max_length=100)),
                ('q3answer', models.CharField(max_length=100)),
                ('q4answer', models.CharField(max_length=100)),
                ('q5answer', models.CharField(max_length=100)),
                ('q6answer', models.CharField(max_length=100)),
                ('q7answer', models.CharField(max_length=100)),
                ('q8answer', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyReview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('lesson', models.IntegerField()),
                ('questionnum', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyReviewAns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('lesson', models.IntegerField()),
                ('questionnum', models.CharField(max_length=100)),
                ('correctoption', models.CharField(max_length=100)),
                ('chooseoption1', models.IntegerField()),
                ('chooseoption2', models.IntegerField()),
                ('chooseoption3', models.IntegerField()),
                ('chooseoption4', models.IntegerField()),
                ('totalchoose', models.IntegerField()),
            ],
        ),
    ]
