# Generated by Django 3.1.1 on 2021-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vocabularyreview_correctans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularypreviewans',
            name='point',
            field=models.FloatField(),
        ),
    ]
