# Generated by Django 3.1.1 on 2021-01-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210129_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularypreview',
            name='questionnum',
            field=models.IntegerField(),
        ),
    ]
