# Generated by Django 3.1.1 on 2021-01-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210129_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularypreview',
            name='falsepercent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vocabularypreview',
            name='numof1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vocabularypreview',
            name='numof2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vocabularypreview',
            name='numof3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vocabularypreview',
            name='numof4',
            field=models.IntegerField(null=True),
        ),
    ]
