# Generated by Django 3.1.1 on 2021-01-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210131_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeyouread',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
