# Generated by Django 3.1.1 on 2021-01-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210131_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='u5beforeyoureadans',
            old_name='numofchoose1',
            new_name='q1answer',
        ),
        migrations.RenameField(
            model_name='u5beforeyoureadans',
            old_name='numofchoose2',
            new_name='q2answer',
        ),
        migrations.RenameField(
            model_name='u5beforeyoureadans',
            old_name='numofchoose3',
            new_name='q3answer',
        ),
        migrations.RenameField(
            model_name='u5beforeyoureadans',
            old_name='numofchoose4',
            new_name='q4answer',
        ),
        migrations.RenameField(
            model_name='u5beforeyoureadans',
            old_name='numofchoose5',
            new_name='q5answer',
        ),
        migrations.RenameField(
            model_name='u7beforeyoureadans',
            old_name='numofchoose1',
            new_name='q1answer',
        ),
        migrations.RenameField(
            model_name='u7beforeyoureadans',
            old_name='numofchoose2',
            new_name='q2answer',
        ),
        migrations.RenameField(
            model_name='u7beforeyoureadans',
            old_name='numofchoose3',
            new_name='q3answer',
        ),
        migrations.RenameField(
            model_name='u7beforeyoureadans',
            old_name='numofchoose4',
            new_name='q4answer',
        ),
        migrations.RenameField(
            model_name='u7beforeyoureadans',
            old_name='numofchoose5',
            new_name='q5answer',
        ),
        migrations.RemoveField(
            model_name='u5beforeyoureadans',
            name='totalchoose',
        ),
        migrations.RemoveField(
            model_name='u7beforeyoureadans',
            name='totalchoose',
        ),
    ]
