# Generated by Django 3.1.1 on 2021-01-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210131_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u5beforeyoureadans',
            name='number',
        ),
        migrations.RemoveField(
            model_name='u7beforeyoureadans',
            name='number',
        ),
    ]
