# Generated by Django 3.1.1 on 2021-01-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210131_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u5beforeyoureadans',
            name='q1answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u5beforeyoureadans',
            name='q2answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u5beforeyoureadans',
            name='q3answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u5beforeyoureadans',
            name='q4answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u5beforeyoureadans',
            name='q5answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u7beforeyoureadans',
            name='q1answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u7beforeyoureadans',
            name='q2answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u7beforeyoureadans',
            name='q3answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u7beforeyoureadans',
            name='q4answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='u7beforeyoureadans',
            name='q5answer',
            field=models.CharField(max_length=255),
        ),
    ]
