# Generated by Django 3.1.1 on 2021-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210131_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeyouread',
            name='numof1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beforeyouread',
            name='numof2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beforeyouread',
            name='numof3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beforeyouread',
            name='numof4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beforeyouread',
            name='numof5',
            field=models.IntegerField(null=True),
        ),
    ]
