# Generated by Django 3.1.1 on 2021-02-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210131_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='U5R1FocusonContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cId', models.CharField(max_length=10)),
                ('q1answer', models.CharField(max_length=255)),
                ('q2answer', models.CharField(max_length=255)),
                ('q3answer', models.CharField(max_length=255)),
                ('q4answer', models.CharField(max_length=255)),
                ('q5answer', models.CharField(max_length=255)),
                ('q6answer', models.CharField(max_length=255)),
                ('point', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='U5R2FocusonContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cId', models.CharField(max_length=10)),
                ('q1answer', models.CharField(max_length=255)),
                ('q2answer', models.CharField(max_length=255)),
                ('q3answer', models.CharField(max_length=255)),
                ('q4answer', models.CharField(max_length=255)),
                ('q5answer', models.CharField(max_length=255)),
                ('point', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='focusoncontent',
            old_name='lesson',
            new_name='reading',
        ),
        migrations.AddField(
            model_name='focusoncontent',
            name='correctans',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='focusoncontent',
            name='option5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='focusoncontent',
            name='questionnum',
            field=models.IntegerField(),
        ),
    ]
