# Generated by Django 3.1.1 on 2021-02-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210201_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FocusOnContentAns',
        ),
    ]
