# Generated by Django 3.1.1 on 2021-02-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_delete_focusoncontentans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabularyReviewAns',
        ),
    ]
