# Generated by Django 3.1.1 on 2021-02-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delete_vocabularyreviewans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VocabularyPreviewAns',
            new_name='U5R1VocabularyPreviewAns',
        ),
    ]
