# Generated by Django 3.1.1 on 2021-02-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20210201_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabularyReview',
        ),
    ]
