# Generated by Django 3.1.1 on 2021-02-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_vocabularyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.IntegerField()),
                ('reading', models.IntegerField()),
                ('questionnum', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('numof1', models.IntegerField(null=True)),
                ('option2', models.CharField(max_length=100)),
                ('numof2', models.IntegerField(null=True)),
                ('option3', models.CharField(max_length=100)),
                ('numof3', models.IntegerField(null=True)),
                ('option4', models.CharField(max_length=100, null=True)),
                ('numof4', models.IntegerField(null=True)),
                ('correctans', models.CharField(max_length=100)),
                ('falsepercent', models.IntegerField(null=True)),
            ],
        ),
    ]
