# Generated by Django 3.1.1 on 2021-02-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_vocabularyreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='U5BeforeYouReadAns',
            new_name='U10BeforeYouReadAns',
        ),
        migrations.RenameModel(
            old_name='U5R1FocusonContentAns',
            new_name='U10R1FocusonContentAns',
        ),
        migrations.RenameModel(
            old_name='U5R1VocabularyPreviewAns',
            new_name='U10R1VocabularyPreviewAns',
        ),
        migrations.RenameModel(
            old_name='U5R1VocabularyReviewAns',
            new_name='U10R1VocabularyReviewAns',
        ),
        migrations.RenameModel(
            old_name='U5R2FocusonContentAns',
            new_name='U10R2FocusonContentAns',
        ),
        migrations.RenameModel(
            old_name='U5R2VocabularyReviewAns',
            new_name='U10R2VocabularyPreviewAns',
        ),
        migrations.RenameModel(
            old_name='U5R2VocabularyPreviewAns',
            new_name='U10R2VocabularyReviewAns',
        ),
        migrations.AlterField(
            model_name='studentcheck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
