# Generated by Django 3.1.1 on 2021-02-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20210203_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='U7BeforeYouReadAns',
        ),
        migrations.DeleteModel(
            name='U7R1FocusonContentAns',
        ),
        migrations.DeleteModel(
            name='U7R1VocabularyPreviewAns',
        ),
        migrations.DeleteModel(
            name='U7R1VocabularyReviewAns',
        ),
        migrations.DeleteModel(
            name='U7R2FocusonContentAns',
        ),
        migrations.DeleteModel(
            name='U7R2VocabularyPreviewAns',
        ),
        migrations.DeleteModel(
            name='U7R2VocabularyReviewAns',
        ),
    ]
