# Generated by Django 3.1.1 on 2021-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20210203_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusoncontent',
            name='numof1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='focusoncontent',
            name='numof2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='focusoncontent',
            name='numof3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='focusoncontent',
            name='numof4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='focusoncontent',
            name='numof5',
            field=models.IntegerField(null=True),
        ),
    ]
