# Generated by Django 3.1.1 on 2021-02-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20210203_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusoncontent',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
