# Generated by Django 3.1.1 on 2021-02-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20210203_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='U10R1FocusonContentAns',
        ),
    ]
