# Generated by Django 3.1.1 on 2021-02-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_u10r1focusoncontentans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='U10R2FocusonContentAns',
        ),
    ]
