# Generated by Django 3.1.1 on 2021-02-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_delete_u10r2focusoncontentans'),
    ]

    operations = [
        migrations.CreateModel(
            name='U10R2FocusonContentAns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cId', models.CharField(max_length=10)),
                ('q1answer', models.CharField(max_length=255)),
                ('q2answer', models.CharField(max_length=255)),
                ('q3answer', models.CharField(max_length=255)),
                ('q4answer', models.CharField(max_length=255)),
                ('q5answer', models.CharField(max_length=255)),
                ('q6answer', models.CharField(max_length=255)),
                ('q7answer', models.CharField(max_length=255)),
                ('q8answer', models.CharField(max_length=255)),
                ('q9answer', models.CharField(max_length=255)),
                ('q10answer', models.CharField(max_length=255)),
                ('point', models.IntegerField(null=True)),
            ],
        ),
    ]
