# Generated by Django 3.1.1 on 2021-02-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_u10r2focusoncontentans'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusoncontent',
            name='falsepercent',
            field=models.IntegerField(null=True),
        ),
    ]
