# Generated by Django 3.1.1 on 2021-02-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_focusoncontent_falsepercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcheck',
            name='focpoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentcheck',
            name='vppoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentcheck',
            name='vrpoint',
            field=models.IntegerField(null=True),
        ),
    ]
