# Generated by Django 3.1.1 on 2021-04-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_vocabularydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcheck',
            name='ctchooseafterdiscuss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentcheck',
            name='ctchoosebeforediscuss',
            field=models.IntegerField(default=0),
        ),
    ]
