# Generated by Django 3.1.1 on 2021-05-03 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_setnaoip'),
    ]

    operations = [
        migrations.AddField(
            model_name='u10beforeyoureadans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 22, 25, 993016)),
        ),
        migrations.AddField(
            model_name='u10r1focusoncontentans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 22, 25, 996044)),
        ),
        migrations.AddField(
            model_name='u10r1vocabularypreviewans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 22, 25, 994012)),
        ),
        migrations.AddField(
            model_name='u10r1vocabularyreviewans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 22, 26, 5015)),
        ),
        migrations.AddField(
            model_name='u10r2focusoncontentans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 22, 25, 996044)),
        ),
        migrations.AddField(
            model_name='u10r2vocabularypreviewans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 22, 25, 994012)),
        ),
        migrations.AddField(
            model_name='u10r2vocabularyreviewans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 22, 26, 5015)),
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 22, 26, 6017)),
        ),
    ]
