# Generated by Django 3.1.1 on 2021-05-04 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20210503_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='u10beforeyoureadans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 11, 13, 27, 892814)),
        ),
        migrations.AlterField(
            model_name='u10r1focusoncontentans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 11, 13, 27, 895804)),
        ),
        migrations.AlterField(
            model_name='u10r1vocabularypreviewans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 11, 13, 27, 893811)),
        ),
        migrations.AlterField(
            model_name='u10r1vocabularyreviewans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 11, 13, 27, 904808)),
        ),
        migrations.AlterField(
            model_name='u10r2focusoncontentans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 11, 13, 27, 896799)),
        ),
        migrations.AlterField(
            model_name='u10r2vocabularypreviewans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 11, 13, 27, 894806)),
        ),
        migrations.AlterField(
            model_name='u10r2vocabularyreviewans',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 11, 13, 27, 905804)),
        ),
    ]
