# Generated by Django 3.1.1 on 2021-05-11 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20210504_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u10r1focusoncontentans',
            name='q10answer',
        ),
        migrations.RemoveField(
            model_name='u10r1focusoncontentans',
            name='q11answer',
        ),
        migrations.RemoveField(
            model_name='u10r1focusoncontentans',
            name='q8answer',
        ),
        migrations.RemoveField(
            model_name='u10r1focusoncontentans',
            name='q9answer',
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 11, 15, 8, 20, 3912)),
        ),
    ]
