# Generated by Django 3.1.1 on 2021-05-11 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20210511_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 11, 15, 46, 26, 326849)),
        ),
    ]
