# Generated by Django 3.1.1 on 2021-05-11 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_auto_20210511_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u10r1focusoncontentans',
            name='q8answer',
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 11, 15, 49, 27, 996513)),
        ),
    ]
