# Generated by Django 3.1.1 on 2021-05-11 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_auto_20210511_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='setnaoip',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 11, 20, 28, 33, 431199)),
        ),
    ]
