# Generated by Django 3.1.1 on 2021-05-25 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_auto_20210525_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 14, 31, 18, 673684)),
        ),
    ]
