# Generated by Django 3.1.1 on 2021-05-25 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_auto_20210525_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetStartTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(max_length=100)),
                ('timezone', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 14, 33, 12, 875004))),
            ],
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 14, 33, 12, 874002)),
        ),
    ]
