# Generated by Django 3.1.1 on 2021-05-26 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_auto_20210526_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customizevocabulary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 12, 55, 34, 272967)),
        ),
        migrations.AlterField(
            model_name='setstarttime',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 12, 55, 34, 272967)),
        ),
    ]
