# Generated by Django 3.1.1 on 2021-05-26 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_auto_20210526_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizevocabulary',
            name='meaning',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customizevocabulary',
            name='partofspeech',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customizevocabulary',
            name='package',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 8, 22, 507401)),
        ),
        migrations.AlterField(
            model_name='setstarttime',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 8, 22, 507401)),
        ),
    ]
