# Generated by Django 3.1.1 on 2021-05-26 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_auto_20210526_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 10, 46, 411345)),
        ),
        migrations.AlterField(
            model_name='setstarttime',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 10, 46, 411345)),
        ),
    ]
