# Generated by Django 3.1.1 on 2021-05-26 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_auto_20210526_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeStudentList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentclass', models.CharField(max_length=20)),
                ('studentid', models.CharField(max_length=20)),
                ('studentname', models.CharField(max_length=20)),
                ('studentgroup', models.IntegerField(null=True)),
                ('studentcheck', models.CharField(default='尚未簽到', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 28, 10, 920991)),
        ),
        migrations.AlterField(
            model_name='setstarttime',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 13, 28, 10, 920991)),
        ),
    ]
