# Generated by Django 3.1.1 on 2021-05-26 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_auto_20210526_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizestudentlist',
            old_name='studentclass',
            new_name='classid',
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 18, 7, 13, 292024)),
        ),
        migrations.AlterField(
            model_name='setstarttime',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 18, 7, 13, 292024)),
        ),
    ]
