# Generated by Django 3.1.1 on 2021-05-27 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_auto_20210526_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizestudentlist',
            name='studentpoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 12, 37, 42, 320895)),
        ),
        migrations.AlterField(
            model_name='setstarttime',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 12, 37, 42, 320895)),
        ),
    ]
