# Generated by Django 3.1.1 on 2021-05-27 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_auto_20210527_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeQuestionAndAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=100)),
                ('questionnum', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100, null=True)),
                ('option4', models.CharField(max_length=100, null=True)),
                ('errorrate', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='setnaoip',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 14, 51, 210749)),
        ),
        migrations.AlterField(
            model_name='setstarttime',
            name='timezone',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 14, 51, 210749)),
        ),
    ]
